---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-ooto-sigs-k8s-io-v1alpha1-module
  failurePolicy: Fail
  name: vmodule.kb.io
  rules:
  - apiGroups:
    - ooto.sigs.k8s.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - modules
  sideEffects: None
