---
apiVersion: ooto.sigs.k8s.io/v1alpha1
kind: Module
metadata:
  name: NAME_CHANGEME
spec:
  driverContainer:
    container:
      modprobe:
        moduleName: KMOD_CHANGEME
      imagePullPolicy: Never
  kernelMappings:
    - literal: KVER_CHANGEME
      containerImage: ooto-kmod:local
  selector:
    wants-oot-module: KMOD_CHANGEME
